# Generated by Django 3.1.3 on 2020-11-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='终端名称')),
                ('eid', models.CharField(max_length=12, unique=True, verbose_name='终端标识')),
                ('type', models.IntegerField(choices=[(1, 'GPS')], verbose_name='终端类型')),
                ('state', models.IntegerField(choices=[(0, '离线'), (1, '在线')], verbose_name='终端状态')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设备',
            },
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=12, verbose_name='终端标识')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='定位时间')),
                ('lng', models.FloatField(verbose_name='经度')),
                ('lat', models.FloatField(verbose_name='纬度')),
            ],
            options={
                'verbose_name': '定位记录',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='线路名称')),
                ('type', models.IntegerField(choices=[(1, '早班车'), (2, '晚班车')], verbose_name='线路类型')),
                ('runningtime', models.CharField(max_length=100, verbose_name='运行时间')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='备注')),
            ],
            options={
                'verbose_name': '班车线路',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='车牌号')),
                ('type', models.IntegerField(choices=[(1, '小巴'), (2, '中巴')], verbose_name='车辆类型')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark2.equipment', verbose_name='定位设备')),
            ],
            options={
                'verbose_name': '车辆',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='站点名称')),
                ('lng', models.FloatField(verbose_name='站点经度')),
                ('lat', models.FloatField(verbose_name='站点纬度')),
                ('orderid', models.IntegerField(verbose_name='站点序号')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark2.route')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathindex', models.IntegerField()),
                ('orderid', models.IntegerField()),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark2.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark2.vehicle', verbose_name='车牌号'),
        ),
        migrations.CreateModel(
            name='Polyline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.TextField()),
                ('orderid', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark2.route')),
            ],
        ),
    ]
