# Generated by Django 3.1.3 on 2020-11-22 12:01

import appipark.utils.myfunc
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='设备ID')),
                ('storage_all', models.FloatField(verbose_name='存储总量(M)')),
                ('storage_free', models.FloatField(verbose_name='可用存储(M)')),
                ('location', models.CharField(max_length=100, verbose_name='设备位置')),
                ('status', models.CharField(max_length=40, verbose_name='设备状态')),
                ('wheel', models.BooleanField(verbose_name='轮播状态')),
                ('start_time', models.CharField(max_length=20, verbose_name='开始时间')),
                ('end_time', models.CharField(max_length=20, verbose_name='结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='素材名称')),
                ('type', models.CharField(max_length=20, verbose_name='素材类型')),
                ('file', models.FileField(upload_to=appipark.utils.myfunc.upload_to_file_path, verbose_name='素材文件')),
                ('thumbnail', models.ImageField(upload_to=appipark.utils.myfunc.upload_to_thumbnail_path, verbose_name='缩略图')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='素材类型')),
                ('name_zh', models.CharField(max_length=20, unique=True, verbose_name='素材类型')),
                ('file_selector_accept', models.CharField(max_length=200, verbose_name='类型选择器')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='分辨率')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='节目名称')),
                ('path', models.CharField(max_length=200)),
                ('storage', models.FloatField(verbose_name='文件大小(M)')),
                ('duration', models.IntegerField(verbose_name='播放时长(秒)')),
                ('json_input', models.CharField(max_length=2000)),
                ('ffmpegcmd', models.CharField(max_length=2000)),
                ('scale_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appipark.scaletype', verbose_name='分辨率')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=40, verbose_name='节目名称')),
                ('equipment', models.CharField(max_length=40, verbose_name='设备ID')),
                ('index', models.IntegerField(verbose_name='列表序号')),
            ],
            options={
                'unique_together': {('program', 'equipment')},
            },
        ),
    ]
