"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l3(zoly2x#a%@s7+04ktj^ui1etlwks@a3*(qcrwt+ad@0a_48'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # 自定义app
    'app.apps.AppConfig',
    'appnpo.apps.AppnpoConfig',
    'appipark.apps.AppiparkConfig',
    'appipark1.apps.Appipark1Config',
    'appipark2.apps.Appipark2Config',
    # 系统app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            # 模板上下文处理器
            'context_processors': [
                # 增加一个debug变量
                'django.template.context_processors.debug',
                # 增加一个request的变量
                'django.template.context_processors.request',
                # 增加了一个user的变量
                'django.contrib.auth.context_processors.auth',
                # 增加了一个messages的变量
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.joinpath('app', 'app.db'),
    },
    'appnpo': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.joinpath('appnpo', 'appnpo.db'),
    },
    'appipark': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.joinpath('appipark', 'appipark.db'),
    },
    'appipark1': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.joinpath('appipark1', 'appipark1.db'),
    },
    'appipark2': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR.joinpath('appipark2', 'appipark2.db'),
    },
}

# 使用多数据库时,需要配置 数据库选择器
DATABASE_ROUTERS = ['app.utils.database_router.DatabaseAppRouter']

# migrate时的对应关系 key:value 分别对应 app_lable 和 database_name 建议取相同的名字
DATABASE_APPS_MAPPING = {
    'appnpo': 'appnpo',
    'appipark': 'appipark',
    'appipark1': 'appipark1',
    'appipark2': 'appipark2',
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR.joinpath('static'),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR.joinpath('media')

# python manage.py collectstatic
# STATIC_ROOT = BASE_DIR.joinpath("static/")

# 设置关闭浏览器session自动过期
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# 使用loginrequired的模块需要定义登录url 不满足条件会自动重定向到此目录
LOGIN_URL = 'ipark1:login'
